spring:
  h2:
    console:
      enabled: 'true'
  datasource:
    url: jdbc:h2:mem:database
caching:
  config:
    user:
      cache-ttl: '10000'
      cache-name: user
    address:
      cache-ttl: '10000'
      cache-name: address
address:
  controller:
    enabled: 'true'
