spring:
  h2:
    console:
      enabled: 'true'
  datasource:
    url: jdbc:h2:mem:database
  profiles:
    active: dev
caching:
  config:
    user:
      cache-ttl: '10000'
      cache-name: user
    address:
      cache-ttl: '10000'
      cache-name: address
address:
  controller:
    enabled: 'true'

resilience4j:
  ratelimiter:
    instances:
      basic:
        limit-for-period: 3
        limit-refresh-period: 1m
        timeout-duration: 5s